name: shovil-wgs-illumina
channels:
 - default
dependencies:
  - bioconda::shovil=1.0.4
  - bioconda::fastp=0.23.2
  - bioconda::multiqc=1.13
  - bioconda::prokka=1.14.6
#  - bioconda::gtdbtk=2.1.1
#  - bioconda::fastani=1.3
#  - conda-forge::perl=5.32.1
#  - conda-forge::libzlib=1.2.13
#  - conda-forge::boost-cpp=1.70
  - conda-forge::r-base=4.2.0
  - conda-forge::r-tidyverse=1.3.2
  - conda-forge::r-remotes=2.4.2
#  - conda-forge::python_abi=3.8
#  - conda-forge::pandas=1.5.2
#  - conda-forge::python=3.8.1

# - bioconda::checkm-genome=1.0.13
# - conda-forge::python=2.7.15
#  - conda-forge::biopython=1.80
