name: shovil-wgs-illumina
channels:
  - default
dependencies:
  - bioconda::shovil=1.0.4
  - bioconda::fastp=0.23.2
  - bioconda::multiqc=1.13
  - bioconda::prokka=1.14.6
  - conda-forge::r-base=4.2.0
  - conda-forge::r-tidyverse=1.3.2
  - conda-forge::r-remotes=2.4.2
  - conda-forge::pandas=1.5.2
  - conda-forge::biopython=1.80
